### ISSUE TITLE
calculation error with weed/paintings

### ISSUE THREAD

**Issue by drummwill** [MichalD96/Perico-heist-goods-counter#10]
according to the calculator, you can click weed 14 times and still have room for painting

this is false, since 14 clicks brings it slightly over half in-game

**Comment by MichalD96** [comment]
That is interesting.
Bag fill steps %:
```javascript
[4.167, 11.111, 8.333, 11.667, 14.167, 15.833, 19.167, 24.167, 29.167, 35.833, 37.5]
```

According to the data in game files 14 clicks is 37.5% + 11.667% = 49.167% of the bag. So painting (that is exactly 50%) should fit perfectly.
I will look at that problem.

I have a plan to rewrite the whole counter, because R* uses different units and the more you mix the targets, the more inaccurate my counter is.
