### ISSUE TITLE
Cayo Good Counter Feedback

### ISSUE THREAD

**Issue by ConstructiveFeedback** [MichalD96/Perico-heist-goods-counter#2]
Couple call outs:
- Your Gold Bag states it fills up 0.7 of a bag when the true number is 0.66
- Same with Cash, instead of 0.3 it should be 0.25.  If it's just a display issue, then change the displayed decimal value to show 2 decimal points so the user can see an accurate value 
- Some of the math doesn't add up correctly.  Here's one case:
No Hard Mode
Pink Diamond = $1,300,000
Gold Stacks 3 (Two full bags) = $1,000,000 ($500,000 x 2)
Total should be = $2,300,000 Max Possible Loot Value
- Also you should incorporate a simple line that deducts the consistent 12% in fees so players know what they are truly getting
- If you want to get fancy, you can add another line asking the user if it is their first time doing the heist as there is no "Fencing Fee" the first time the user completes the Heist

**Comment by MichalD96** [comment]
> Your Gold Bag states it fills up 0.7 of a bag when the true number is 0.66

yes, it is to simplify everything, 0.66 may be confusing for ppl because in-game bar has accuracy 0.05 % of the bag.

> Same with Cash, instead of 0.3 it should be 0.25.

Cash is exactly 0.25 https://michald96.github.io/Perico-heist-goods-counter/data/targets.json
and it is good idea to change display to 2 decimal points

> Some of the math doesn't add up correctly. 

The difference is less than 4K $ and it is because i use average value of the items. Evey item has minimum and maximum price:
Gold = $333k to $329k
Coke = $225k to $220k
Arts = $200k to $175k
Weed = $150k to $145k
Cash = $95k to $90k

> Also you should incorporate a simple line that deducts the consistent 12% in fees so players know what they are truly getting

I have that in plans! 

> If you want to get fancy, you can add another line asking the user if it is their first time doing the heist as there is no "Fencing Fee" the first time the user completes the Heist

I will show it as "potential take" then "fencing fee" and "max possible final cut"

**Comment by MichalD96** [comment]
Added / fixed most things from your suggestions 😉
