### ISSUE TITLE
Slight adjustments

### ISSUE THREAD

**Issue by LemonMelon3001** [MichalD96/Perico-heist-goods-counter#4]
Great website, really helpful for heist prep

Just a couple of things, the percentages are wrong on the secondary targets, weed is 33% not 25%, cash is 25% not 15%, and cocaine and paintings are 50% and gold is 66%

**Comment by MichalD96** [comment]
> Great website, really helpful for heist prep

Thank you!

Percentages are correct on the site. Weed is 37.5% not 33%.
If you reset all targets to 0, and then add single stack of each target to your inventory you will see this values:
  - gold: 0.65 bag,
  - coke: 0.50 bag,
  - weed: 0.40 bag,
  - painting: 0.50 bag,
  - cash: 0.25 bag
All values are from the game files. And my script recreate the same mechanics. Look that picking up some stuff like cash is not linear, in first click you pick up only one cash bundle, and in 7th click you swipe half of the table, my script take that in to account too.
Values are rounded to the closest multiple of 5, because this is how counter in game works. (37.5 rounded to 40, 66.(6) rounded to 65). If this does not explain how the counter works, i don't know what you mean.
