### ISSUE TITLE
Incorrect max profit calculations

### ISSUE THREAD

**Issue by kuber01** [MichalD96/Perico-heist-goods-counter#5]
I'm not sure, but for some reason, if I add 1 weed stack and 1 painting with, let's say, Tequila, it says I should fill my bag with 0.9 capacity and my max profit is $1.241.004. But when I add another weed stack, it says that I should fill my bag with 0.75 weed bags, which makes my max profit $1.205.516. I'm not sure why, because with 2 weed stacks and 1 painting it clearly better to choose the first option, but the calculator doesn't think so.

**Comment by MichalD96** [comment]
Hey
Site shows the most profitable combination per picked up item unit. This is because on the island is always more loot than 4 players can pick up. Weed is worth much more than painting, and when you pick up 2 stacks of weed, there is not enough space for painting. 
This is intended behavior, but i agree that not intuitive, i will add the setting to prefer bag fill over the highest profit.
I know this is important because of elite challenge.

**Comment by MichalD96** [comment]
I updated the site, from now site prefer to fill the bag, the only exception is gold and coke that are more profitable in any other combination (even with the rest of cash).
I think it is the best balance between (bag fill/max possible profit)
